twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        tricks_to_show: '%app.nb_tricks_to_show%'
when@test:
    twig:
        strict_variables: true
